// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_MembershipType_Table_With_Name_Values : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_MembershipType_Table_With_Name_Values));
        
        string IMigrationMetadata.Id
        {
            get { return "201708042125565_Update_MembershipType_Table_With_Name_Values"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
